In [19]:
import numpy as np
import math

In [20]:
A = np.array([[2, 4, 6], [1, 3, 5], [7, 9, 11]])
B = np.array([[8, 5, 2], [7, 4, 1], [6, 3, 0]])

In [22]:
elements_wise_sum = A + B
elements_wise_product = A * B
dot_product = np.dot(A, np.transpose(B))
determinant_of_A = float(np.linalg.det(A))

In [33]:
print(f"Elements wise sum(A+B):\n {elements_wise_sum}")
print(f"\nElements wise product(AxB):\n {elements_wise_product}")
print(f"\nDot product of (A.B^t):\n {dot_product}")
print(f"\nDeterminant of A: {determinant_of_A}")

Elements wise sum(A+B):
 [[10  9  8]
 [ 8  7  6]
 [13 12 11]]

Elements wise product(AxB):
 [[16 20 12]
 [ 7 12  5]
 [42 27  0]]

Dot product of (A.B^t):
 [[ 48  36  24]
 [ 33  24  15]
 [123  96  69]]

Determinant of A: 0.0
